# Generated by Django 4.2 on 2023-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NR', 'Normal'), ('WD', 'Wide'), ('DM', 'Diamond'), ('Ex', 'Explosive'), ('SS', 'Side to Side'), ('CP', 'Clapping'), ('Ar', 'Archer'), ('OC', 'Open Close'), ('TW', 'TypeWriter'), ('ST', 'Shoulder Tap')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reps', models.IntegerField()),
            ],
        ),
    ]
