# Generated by Django 4.2 on 2023-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushups', '0002_pushup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushup',
            name='name',
            field=models.CharField(choices=[('NR', 'Normal'), ('WD', 'Wide'), ('DM', 'Diamond'), ('EX', 'Explosive'), ('SS', 'Side to Side'), ('CP', 'Clapping'), ('AR', 'Archer'), ('OC', 'Open Close'), ('TW', 'TypeWriter'), ('ST', 'Shoulder Tap')], max_length=2),
        ),
    ]
