# Generated by Django 4.2 on 2023-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(),
        ),
    ]
