# Generated by Django 4.2 on 2023-04-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0006_alter_todo_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="added",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="content",
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("D", "Doing"), ("C", "Completed")], default="D", max_length=5
            ),
        ),
    ]
