# Generated by Django 4.2 on 2023-04-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gravatar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gravatar_link',
            field=models.URLField(null=True),
        ),
    ]
