# Generated by Django 4.2 on 2023-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_gravatar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quote_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
