# Generated by Django 4.2 on 2023-04-07 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_simon_newsletter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="simon_newsletter",
            new_name="public",
        ),
    ]
