# Generated by Django 4.2 on 2023-04-09 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="requested_friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
