# Generated by Django 4.2 on 2023-04-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_requested_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='public',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='quote_newsletter',
        ),
    ]
