# Generated by Django 4.2 on 2023-04-25 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
