# Generated by Django 4.2 on 2023-04-16 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_notification_read"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
