# Generated by Django 4.2 on 2023-04-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "content",
                    tinymce.models.HTMLField(blank=True, max_length=2000, unique=True),
                ),
                ("author", models.CharField(blank=True, max_length=50)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("EN", "English"), ("PL", "Polish")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                (
                    "approved",
                    models.CharField(
                        choices=[
                            ("AP", "Approved"),
                            ("WT", "Waiting"),
                            ("RJ", "Rejected"),
                        ],
                        default="WT",
                        max_length=2,
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
