# Generated by Django 4.2 on 2023-04-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('PL', 'Polish')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
