# Generated by Django 4.2 on 2023-04-06 08:53

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='content',
            field=django_quill.fields.QuillField(default='m'),
            preserve_default=False,
        ),
    ]
