# Generated by Django 4.2 on 2023-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_quote_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="quote",
        ),
        migrations.AddField(
            model_name="quote",
            name="content",
            field=models.TextField(default="a"),
            preserve_default=False,
        ),
    ]
