# Generated by Django 4.2 on 2023-04-06 10:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_quote_quote_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
