# Generated by Django 4.2 on 2023-04-07 15:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_alter_quote_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="content",
            field=tinymce.models.HTMLField(unique=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
