# Generated by Django 4.2 on 2023-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_quote_favorites_alter_quote_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("PL", "Polish")], max_length=2
            ),
        ),
    ]
