# Generated by Django 4.2 on 2023-04-10 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotes", "0007_alter_quote_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="quote",
            name="content",
            field=tinymce.models.HTMLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("EN", "English"), ("PL", "Polish")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="title",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
