# Generated by Django 4.2 on 2023-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0008_alter_quote_author_alter_quote_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("EV", "ALL"), ("EN", "English"), ("PL", "Polish")],
                default="EV",
                max_length=2,
                null=True,
            ),
        ),
    ]
