# Generated by Django 4.2 on 2023-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0010_alter_quote_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
