# Generated by Django 4.2 on 2023-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0011_quote_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="approved",
            field=models.CharField(
                choices=[("AP", "Approved"), ("WT", "Waiting"), ("DC", "Declined")],
                default="WT",
                max_length=2,
            ),
        ),
    ]
