# Generated by Django 4.2 on 2023-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0012_quote_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="approved",
            field=models.CharField(
                choices=[("AP", "Approved"), ("WT", "Waiting"), ("RJ", "Rejected")],
                default="WT",
                max_length=2,
            ),
        ),
    ]
