# Generated by Django 4.2 on 2023-04-22 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0013_alter_quote_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="added",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="modified",
        ),
    ]
